name: Test Project
on:  push
jobs:
  test:
    runs-on: ubuntu-latest  # this server don't have code to run
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          node-version: 18
          submodules: 'true'
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test